---
title: "Literature Review"
output: pdf_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Literature Review

As both traffic and pedestrian stop data have become more readily available to the public, researchers have explored novel methods of testing for discrimination. The fundamental problem of traffic stop data is the lack of accompanying traffic data – although we know who was stopped in a given time and location, we do not know the fellow motorists of this unlucky motorist who was pulled over. If we consistently find that this unlucky motorist is black or Hispanic/Latinx while his/her/their fellow motorists are white, then this may provide evidence of racial profiling. However, the demographic information of these fellow motorists remains unknown. The lack of a denominator (which would convey who else is driving at a given time and location) has motivated a range of attempts to circumvent the baseline driving population through natural experiments, experimental designs, and analyses of post-stop outcomes. 


As researchers and social scientists continue to drive the progress of assessing racial bias in police practices around the country, it is important to note that a majority of the current methods of assessments do not meet the basic assumptions of causal inference. @ridgeway2010 discusses benchmarks (external vs internal) and how various analyses use them as a tool to assess the prevalence of racial bias but in fact may be responsible either hiding evidence of or exaggerating the practice. First, consider the use of external benchmarks. External benchmarks can be understood as concrete observations of traffic stops. In this study, every variable in the dataset describing an observation is an external benchmark. External benchmarks are useful because they enable an analysis to estimate the at-risk population distribution in terms of traffic stops. As a result, external benchmarks can be useful in building a robust model, however, it can also overlook indirect factors that may motivate the manifestation of what many are calling police discrimination. 

Ridgeway points out that internal benchmarks are an essential consideration as well in assessing racial bias in policing practices. In the context of traffic stops, internal benchmarks can be understood as thresholds or conditions that individual police officers may have that determine whether a stop happens or the stop outcome. In fact, considering such motivations is important in deciphering if racial bias is systematic or more in fact prevalent on an individual officer basis. Furthermore, in some cases racial differences did not depend on the race of the driver. From an audit of 313 vehicle-mounted video and audio recordings of the Cincinnati Police Department, the policing practices were more partisan based on the race of the police officer which contributes to the claim that policing racial bias may be more individualized than is communicated. From understanding how different benchmarks can be used to assess if policing bodies are racially bias, it is increasingly clear that developing more definitive tests of racial profiling continues to be a work in progress. In fact, it’s social and political relevance has been present in the United States for the past few decades. From cases such as Terry v. Ohio the negotiation of protecting Fourth Amendment rights of minority defendants has been an ongoing area of interest. @goel2017 introduces the idea of taking advantage of ‘the second information age’, leveraging big data and statistical modeling to find statistical evidence of these racial disparities, validating the various qualitative anecdotes heard around the country of oppression, brutality and injustice.


The enactment of seatbelt laws presented a natural experiment in the context of traffic stops. With an analysis of stops pre and post legislative change, we can compare the magnitude to which the legislation affects the number of stops for different racial groups. @riddell2020 performed this study looking at South Carolina’s 2006 seat belt law, which enabled police troopers to conduct traffic stops for drivers who aren’t wearing a seat belt. Traffic stops conducted due to an observed violation (as opposed to due to speeding) increased between 2005 and 2006. For white and Hispanic drivers, this was a 50% increase; for Black drivers, this was a 58% percent increase. However, because the number of traffic stops changed, Black arrest rates decreased while Hispanic arrest rates increased.


Furthermore, taking advantage of natural variation of traffic patterns between daytime and nighttime has shown to have an effect on traffic patterns. @kalinowski2019 found that the types of stops made by the police vary considerably between daytime and night-time. When daytime transforms into night-time, the number of speeding stops is reduced, while the number of equipment warning stops is increased. There also seems to exist a location shift of traffic stops, which indicates that the geographical distribution of police officers changes throughout the course of a day — some regions enjoy a higher share of manpower during the daytime, whereas some other regions enjoy a higher share of manpower during the night-time. It was also observed that counties receiving more police resources during the night-time have a higher share of minority residents.


Discrepancies of search rates became of interest through the analysis of stop-and-frisk rates. @goel2016 studied the varying hit rates dependent on race of the driver with particular focus on suspicion of criminal possession of a weapon (CPW) stops. The results indicate a predominantly black and Hispanic demographic for incorrect presumption for a stop — correct hits accounted for 2.5% and 3.6% of CPW stops for black and Hispanic suspects respectively and 11% for white suspects. This discrepancy may suggest differences in the likelihood of stop and search for each demographic due to biased levels of suspicion.


Much of previous literature including @grogger2006, @taniguchi2017, and @pierson2020 introduce logistic regression as an effective method of predicting traffic stop outcomes from the variables available. All incorporate different numbers of variables in order to calculate the probability of a driver stopped in the context of the veil of darkness (VOD) model, specifically drivers grouped by race. Additionally, something to consider is the notion of differing police behaviors during night and day can also be factored into logistic regression. Another natural experiment opportunity results with marijuana legalization and changes in enforcement of driving infractions, namely seat belt laws. Riddell 2020 proposes using seat belt laws to overcome the unknown denominator which has been pointed out by previous literature. The former results in less stops, the latter results in more stops. Either way, we can compare the magnitude to which these legislative changes affect the number of stops for different racial groups.


Another body of literature focuses on pedestrian stops, which has the benefit of being more detailed with the location of the stop and the type of location that the stop is. There are less studies in this category probably due to limited data, but for the data that does exist, it is quite extensive @goel2016 @hannon2019. We see a similar baseline problem of – we do not know who the fellow pedestrians are and the issue of consistent data collection is also apparent.
	
Lastly, the last category of literature we have considered is literature concerning the racial disparities in traffic stop outcomes. @shoub2017 explores how greater black political representation has an inhibitory effect on what happens during a stop and after a stop when compared with other less black represented districts. Even more interesting is that @rosenfeld2012 explores how considering age in combination with race significantly shows disparities in traffic stop activity and outcomes. This is the primary focus of this project’s exploratory nature. 


